; VT100 escape sequences. See http://www.termsys.demon.co.uk/vtansi.htm
(define esc (number->byte 27))
(defun curnopar (s) (string-append esc s))
(defun curonepar (n s) (string-append esc "[" (number->string n) s))
(defun curtwopar (a b s) (string-append esc "[" (number->string a) ";"
                          (number->string b) s))
(defun cur-home () (curnopar "[H"))
(defun cur-xy (x y) (curtwopar x y "f"))
(defun cur-up (y) (curonepar y "A"))
(defun cur-down (y) (curonepar y "B"))
(defun cur-left (y) (curonepar y "D"))
(defun cur-right (y) (curnopar y "C"))
(defun cur-save () (curnopar "[s"))
(defun cur-restore () (curnopar "[u"))
(defun clr-screen () (curnopar "[2J"))
(defun clr-to-eol () (curnopar "[K"))
(defun clear-to-sol () (curnopar "[1K"))
(defun clear-row () (curnopar  "[2K"))
(defun clear-above () (curonepar "[1J"))
(defun clear-below () (curonepar "[J"))
(defun clear-attribs () (curonepar "[0m"))
(defun scroll (s e) (curtwopar s e "r"))
(defun scroll-down () (curonepar "D"))
(defun scroll-up () (curonepar "M"))
(prn (clr-screen))
(prn (cur-xy 0 0))
(prn "Testing VT100 escape sequences")
(sleep 10)
